name: Publish NPM Package

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  npm-publish:
    uses: devshareacademy/shared-workflows/.github/workflows/pnpm-publish-package.yml@main
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
      gh_token: ${{ secrets.GH_TOKEN }}
