name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
        env:
          CI: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: pnpm lint
        run: pnpm lint
        env:
          CI: true

      - name: pnpm build
        run: pnpm build
        env:
          CI: true

      - name: pnpm test
        run: pnpm test
        env:
          CI: true
